substitutions:
  name: clack
  device_description: "Esphome component for Clack WS1 softener with TOF sensor saltlevel detection"
  timezone: "Europe/Amsterdam"  

# In order to use other language or a different ESP chip, fix include file name below:
# Currently supported languages are en (english), nl (dutch). 
# ESP32-wemos-s3 is a wemos lolin S3 mini

packages:
  remote_package:
    url: https://github.com/fonske/clack-reader-v3
    ref: main
    files: 
      #- esphome/.clack-labels-en.yaml
      - esphome/.clack-labels-nl.yaml
      - esphome/board-esp32-wemos-s3.yaml

esphome:
  name: ${name}
  on_boot:
    priority: 200
    then:
      - script.execute: on_boot

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  services:
    - service: meterstand_clack
      variables:
        meter_value: float
      then:
        - globals.set:
            id: totalWaterUsage
            value: !lambda "return ( meter_value ) ;"

time:
  - platform: sntp
    id: clack_sntp_time
    timezone: ${timezone}

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: "configesp"
    ap_timeout: 15s

globals:
  - id: totalWaterUsage
    type: float
    restore_value: yes          
    initial_value: '00' 

# Define a global variable for the chlorinator delay duration in minutes
  - id: duration
    type: int
    restore_value: yes
    initial_value: '05'


script:
###  On reboot or powerloss of the esp, set the time left counter
  - id: on_boot
    then:
      - text_sensor.template.publish:
          id: clack_regeneration_last
          state: !lambda |-
            char str[32];
            time_t currTime = id(clack_sntp_time).now().timestamp;
            strftime(str, sizeof(str), "%a %d %b %H:%M", localtime(&currTime));
            return  { str };

###  Define a script that turns on the chlorinator relay, waits for the duration, and turns it off
  - id: chlorinator_start
    mode: restart
    then:
      - switch.turn_on: chlorinator_relay
      # Use a lambda expression to return the delay in milliseconds
      - delay: !lambda "return id(duration) * 60 * 1000;"
      - switch.turn_off: chlorinator_relay

light:
#G47=RGB WS2812C-2020
  - platform: esp32_rmt_led_strip
    name: Led
    id: led
    rgb_order: GRB
    pin: 47
    num_leds: 4
    # RMT 0 channels will be occupied by IR
    rmt_channel: 1
    chipset: ws2812
    restore_mode: RESTORE_DEFAULT_ON

#-----------
#SENSORS
#-----------
sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "Current"
    power:
      name: "Power"
      filters:
        - delta: 0.05
    bus_voltage:
      name: "Voltage"
    shunt_voltage:
      name: "Shunt Voltage"
    max_voltage: 32.0V
    max_current: 3.2A
    update_interval: 5s

  - platform: vl53l0x
    id: distance_cm
    address: 0x29
    update_interval: 5s
    long_range: false
    internal: false
    filters:
      - filter_out: nan
      - lambda: return x*100;
      - median:
          window_size: 15
          send_every: 7
          send_first_at: 1
      - delta: 0.5
      - clamp:
          min_value: 0.0
          max_value: 160.0
    on_value:
      then:
        - sensor.template.publish:
            id: clack_distance
            state: !lambda |-
              return id(distance_cm).state;

# ultrasonic distance sensor.
  - platform: template
    name: ${clack_distance}
    id:  clack_distance
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    icon: "mdi:arrow-expand-vertical" 
    on_value:
      then:
        - sensor.template.publish:
            id: clack_procent
            state: !lambda |-
              const float max_distance = id(clack_saltlevel_height_max).state; // heigt in cm to lowest level
              const float min_distance = id(clack_saltlevel_height_min).state; // height in cm to highest level
              return int((1-((id(clack_distance).state - min_distance)/max_distance))*100);
        - sensor.template.publish:
            id: clack_height
            state: !lambda |-
              const float max_distance = id(clack_saltlevel_height_max).state;  // height in cm to lowest level
              return max_distance-id(clack_distance).state;
        - text_sensor.template.publish:
            id: clack_fill_salt
            state: !lambda |-
              if (id(clack_height).state < id(clack_saltlevel_height_fill).state) {
                return {"${clack_yes}"};
              } else {
                return {"${clack_no}"};
              }
    
      
  # ultrasonic distance sensor calculate tank_percentage
  - platform: template
    id: clack_procent
    name: ${clack_procent}
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:percent-box-outline" 
    update_interval: 600s
    filters:
    - lambda: |-
        if (x >= 100) return 100.0;
        else if (x <= 0.0) return 0.0;
        else return x;

  # Saltlevel animation picture on dashboard  
  - platform: copy
    source_id: clack_procent
    id: clack_salt_level
    name: "Salt level"
    filters:
    - lambda: |-
        if (x >= 80) return 100;
        else if (x >= 65 && x <= 79) return 80;
        else if (x >= 40 && x <= 64) return 60;   
        else if (x >= 20 && x <= 39) return 40;
        else if (x >= 10 && x <= 19) return 20;
        else if (x >= 5 && x <= 9) return 10;
        else if (x <= 4) return 0;
        else return x;

          
  # ultrasonic distance sensor calculate salt level from bottom
  - platform: template
    id: clack_height
    name: ${clack_height}
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    icon: "mdi:hydraulic-oil-level" 
    update_interval: 600s
    filters:
    - lambda: |-
        if (x >= 100) return 100.0;
        else if (x <= 0.0) return 0.0;
        else return x;


#####################################################################
# CLACK
#####################################################################

#  Watermeter  
  - platform: template
    id: clack_watermeter
    name: ${clack_watermeter_total}
    state_class: "total_increasing"
    icon: mdi:water
    update_interval: 600s
    unit_of_measurement: "l"
    accuracy_decimals: 0
    lambda: |-
      return id(totalWaterUsage);

  - platform: template  
    id: clack_m3_left
    name: ${clack_m3_left}
    unit_of_measurement: 'm3'
    accuracy_decimals: 2
    update_interval: 600s

  - platform: template
    id: clack_l_left
    name: ${clack_l_left}
    unit_of_measurement: 'l'
    accuracy_decimals: 0
    update_interval: 600s

# Diagnostics wifi and uptime      
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: clack_wifi_signal_db
    name: "WiFi Signal dB"
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: clack_wifi_signal_db
    id: clack_wifi_signal_db_percent
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

  - platform: uptime
    id: clack_uptime
    name: ${clack_uptime}
    unit_of_measurement: ${days}
    update_interval: 3600s
    accuracy_decimals: 1
    filters:
      - multiply: 0.000011574

switch:
## Chlorinator Relay
  - platform: gpio
    pin:
      number: 10
      inverted: false
    name: Clorinator
    id: chlorinator_relay
    icon: mdi:alarm-bell

select:
  - id: clack_select_chl_or_dpsw
    name: ${clack_select_chl_or_dpsw}
    platform: template
    options:
      - "Uit"     
      - "Chlorinator"
    initial_option: "Uit"
    optimistic: true

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    id: clack_version
    name: ${clack_version}
    hide_timestamp: true

  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${clack_ip}
      icon: mdi:ip-network

  # Textsensor "Fill Salt" yes or no.
  - platform: template
    name: ${clack_fill_salt}
    id: clack_fill_salt
    icon: mdi:basket-fill
    update_interval: never

# imput numbers as sliders for setting the dimensions of the tank and level alarm.
number:
    ## Set minimum distance (from bottom sensor / above plastic cap)
  - platform: template
    id: clack_saltlevel_height_min
    name: ${clack_saltlevel_height_min}
    icon: mdi:toggle-switch-variant
    optimistic: true
    mode: slider
    step: 0.5
    entity_category: config
    min_value: 0
    max_value: 10
    initial_value: 0
    restore_value: yes
    unit_of_measurement: "cm"
    on_value:
      then:
        - sensor.template.publish:
            id: clack_procent
            state: !lambda |-
              const float max_distance = id(clack_saltlevel_height_max).state; // heigt in cm to lowest level
              const float min_distance = id(clack_saltlevel_height_min).state; // height in cm to highest level
              return int((1-((id(clack_distance).state - min_distance)/max_distance))*100);
        - sensor.template.publish:
            id: clack_height
            state: !lambda |-
              const float max_distance = id(clack_saltlevel_height_max).state;  // height in cm to lowest level
              return max_distance-id(clack_distance).state; 

    ## Set maximum distance (from bottom sensor / underneath plastic cap) to water level (to measure in pipe?)
  - platform: template
    id: clack_saltlevel_height_max
    name: ${clack_saltlevel_height_max}
    icon: mdi:toggle-switch-variant-off
    optimistic: true
    mode: slider
    step: 0.5
    entity_category: config
    min_value: 0
    max_value: 100
    initial_value: 30
    restore_value: yes
    unit_of_measurement: "cm"
    on_value:
      then:
        - sensor.template.publish:
            id: clack_procent
            state: !lambda |-
              const float max_distance = id(clack_saltlevel_height_max).state; // heigt in cm to lowest level
              const float min_distance = id(clack_saltlevel_height_min).state; // height in cm to highest level
              return int((1-((id(clack_distance).state - min_distance)/max_distance))*100);
        - sensor.template.publish:
            id: clack_height
            state: !lambda |-
              const float max_distance = id(clack_saltlevel_height_max).state;  // height in cm to lowest level
              return max_distance-id(clack_distance).state;

    ## Set alarm level
  - platform: template
    id: clack_saltlevel_height_fill
    name: ${clack_saltlevel_height_fill}
    icon: mdi:hydraulic-oil-temperature
    optimistic: true
    mode: slider
    step: 0.1
    entity_category: config
    min_value: 0
    max_value: 10
    initial_value: 1.5
    restore_value: yes
    unit_of_measurement: "cm"
    update_interval: 600s
    on_value:
      then:
        - text_sensor.template.publish:
            id: clack_fill_salt
            state: !lambda |-
              if (id(clack_height).state < id(clack_saltlevel_height_fill).state) {
                return {"${clack_yes}"};
              } else {
                return {"${clack_no}"};
              }

    ## Set capacity liters
  - platform: template
    id: clack_capacity_liters
    name: ${clack_capacity_liters}
    icon: mdi:water-opacity
    optimistic: true
    mode: slider
    step: 50
    entity_category: config
    min_value: 0
    max_value: 7200
    initial_value: 3200
    restore_value: yes
    unit_of_measurement: "l"
    on_value:
      then:
        - sensor.template.publish:
            id: clack_watermeter
            state: !lambda |-
              return id(totalWaterUsage);
        - sensor.template.publish:
            id: clack_m3_left
            state: !lambda |-
              return float(id(clack_capacity_liters).state - id(clack_watermeter).state) * 0.001;
        - sensor.template.publish:
            id: clack_l_left
            state: !lambda |-
              return int(id(clack_capacity_liters).state - id(clack_watermeter).state);
  
    ## Set capacity days  
  - platform: template
    id: clack_capacity_days
    name: ${clack_capacity_days}
    icon: mdi:calendar-clock
    optimistic: true
    mode: slider
    step: 1
    entity_category: config
    min_value: 0
    max_value: 21
    initial_value: 10
    restore_value: yes
    unit_of_measurement: "days"

  ## Set chlorinator relay off-delay
  - platform: template
    id: clack_chlorinator_delay
    name: ${clack_chlorinator_delay}
    icon: mdi:toggle-switch-variant
    optimistic: true
    mode: slider
    step: 1
    entity_category: config
    min_value: 0
    max_value: 15
    initial_value: 5
    restore_value: yes
    unit_of_measurement: "min"
    on_value:
      then:
        - globals.set:
            id: duration
            value: !lambda 'return int(x);'